### ISSUE TITLE
Automatically define Julia functions for TensorFlow ops

### ISSUE THREAD

**Issue by malmaud** [malmaud/TensorFlow.jl#195]
I realized that since we have protobufs that describe the inputs and outputs of all TensorFlow operations, we could use some metaprogramming magic to automatically generate Julia functions for wrapping many of the operations and eliminate a lot of the boilerplate of the code in `ops/`. This will be my next TensorFlow.jl project once I get the dynamic_rnn branch merged.

**Comment by oxinabox** [comment]
You are aware of: https://github.com/benmoran/TensorFlow.jl and https://github.com/benmoran/TensorFlowBuilder.jl ?
(It is a bit unmaintained) I think kind of related.
It is generating from the Python definitions rather than the protobufs, I think.



Would you be thinking of having a nonexported "API" or "RawOps" submodule with 100% of everything,
and then depending on the operation, either reexporting it,
or writing a exported wrapper around it that does things like fix indexing?

Or would it be more having a function/macro that retrieves the definition of a specified function from  the protobuf, and just defines that one, which is known to be sane, and not need special wrapper code.

**Comment by malmaud** [comment]
> Would you be thinking of having a nonexported "API" or "RawOps" submodule with 100% of everything,
and then depending on the operation, either reexporting it,

Yes, exactly.

**Comment by malmaud** [comment]
Also see https://www.tensorflow.org/versions/r1.1/extend/language_bindings, which explicitly recommends this approach.

**Comment by oxinabox** [comment]
Any update on the status of this?

**Comment by malmaud** [comment]
Still working on it; there were a surprising number of subtleties. Should be done pretty soon.

**Comment by malmaud** [comment]
Done
