### ISSUE TITLE
Example snippets in README.md not working.

### ISSUE THREAD

**Issue by wolfiex** [malmaud/TensorFlow.jl#206]
> ERROR: UndefVarError: global_variables_initializer not defined

Tensorflow installed by python globally, 
shared env with pycall (can use pyimport), 
and Jl package freshly installed and updated in Julia 5.

**Comment by malmaud** [comment]
It's called `initialize_all_variables` in the current release version.

**Comment by oxinabox** [comment]
Should probably tag a new version that has that syntax

**Comment by oxinabox** [comment]
This has in general always been an issue with Readme's on github.
Since github shows the default branch's readme as  on the project home page.
And the default branch is _master_.

The readme is correct for _master_.

Possible general solutions:

 - change the default branch in settings
 - Have masters have a second readme file called `README.current_branch.md`, and have `README.md` used only for the last release -- then do an update per release.
 - Not have any examples in the readme, and have a link to Docs-Release, and Docs-latest

**Comment by malmaud** [comment]
Readme is in sync with the released version now.
