### ISSUE TITLE
Use Conda.jl to install Python TensorFlow

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#252]
It should be very easy to install the Python TensorFlow using Conda.jl
Probably only adding 2 lines to `build.jl`

Is there any reason not to do this?
It would make the setup easier for new users since they won't have to worry about installing anything.

**Comment by malmaud** [comment]
Ya, let's do it.

**Comment by abhi18av** [comment]
@malmaud  and @oxinabox Yeah, please do consider this option it could be really handy. Atm I have tensorflow installed via conda and thus the python wrappers but since I do need to explore some data using `R`,  I installed the RStudio's tensorflow library as well. It did't need to reinstall anything at all, located the local installation by itself.

It'd be really nice to just have this kind of smooth installation in julia based wrapper as well 👍

**Comment by abhi18av** [comment]
Or have I not configured things properly ?

**Comment by oxinabox** [comment]
> Or have I not configured things properly ?

Yes, if you already have tensorflow installed for python,
but tensorflow.jl isn't working,
then that sounds like   `ENV["PYTHON"]` is not set to the right python for PyCall.
See [here](https://github.com/JuliaPy/PyCall.jl#specifying-the-python-version).

What using Conda.jl would do, is kinda the opposite,
if `ENV["PYTHON"]==""` then it would install a new tensorflow, and a new copy of python, in a new conda repo.
Which is easy and smooth, even thought it does mean hauling like half a gig of redundant stuff down the internet.

**Comment by aterenin** [comment]
Just a quick note that the version of TensorFlow installed by Conda.jl may not be the latest one. The one on my system installed with Conda.jl is 1.0.0, whereas the binary used by the TensorFlow.jl is 1.1.0.

**Comment by abhi18av** [comment]
Yeah, and I noticed that it's really important to update Package Metadata
after installing the juliaPro distribution.


Got it working fine now :)
