### ISSUE TITLE
Minor(?) issue/question and broken link pointer

### ISSUE THREAD

**Issue by PallHaraldsson** [malmaud/TensorFlow.jl#3]
README: "A wrapper around Tensorflow" that link doesn't work..

Above that text "build failing". [I'm not sure, if it is related.. or a reflection on TensorFlow.jl or the Python Tensorflow package (or even the C code it's built on..).]

I would like to know if this "build failing" is a reason to stay away from TensorFlow.jl (or just a problem on master) and in general if it is as good as the Python package?Does it have the same (complete?) API? Comparable enough, while maybe tutorials you would find for Python/TensorFlow find would not work identically?

That is, I do not know much about TensorFlow (or Google's TensorUnits hardware), just that it is popular.. and is this as good a substitute? [And is Julia more-or-less 1) a good substitute from ANN-work to Python 2) and for data-science in general..? I guess you feel at least Julia valuable, I'm thinking if I can recommend Julia (over Python), if not in general then for what purposes.]

**Comment by malmaud** [comment]
Thanks for the pointer about the link - it's fixed now. 

The problem with the build failing is just because you have to have Python installed with tensorflow at the moment, which the testing server doesn't have. It actually works fine - give it a shot. 

I'm rapidly expanding it's coverage of the TensorFlow API. Right now it covers the most important API functions, but there are many obscure ones left to be wrapped.

Since the Python Tensorflow package and this package are both wrapping the same underlying C library, it should be at least as good.

**Comment by PallHaraldsson** [comment]
"should be at least as good" you mean it could be or know for sure? [Stuff that you've actually wrapped should be as good. Python wrapper could have wrapped more, or not.]

**Comment by malmaud** [comment]
I mean, it's not as good right now as the Python wrapper since it doesn't
wrap everything yet. I just mean in principle it could be as good since it
wraps there same library.
