### ISSUE TITLE
Issues in setting up dev environment

### ISSUE THREAD

**Issue by RatanRSur** [malmaud/TensorFlow.jl#329]
I don't know if these are documented or expected but I can put together a pull request to fix them if you feel like they are actually issues.

I think it could be better documented that running `test/runtests.jl` will fail if `deps/build.jl` has not been run.

`build.jl` copies `tensorflow.so` to `usr/bin/tensorflow.dylib` but it seems like it should go to `/usr/bin/tensorflow.dylib`. Even when the path is made absolute, I still get a permission issue.

**Comment by oxinabox** [comment]
`usr/bin/tensorflow.dylib` is correct.
To be more precise, on most unix-ish systems `~/.julia/v0.6/TensorFlow/deps/usr/bin/tensorflow.dylib` is the target location.


The normal way to use **any** Julia package is to run from the Julia REPL:
`Pkg.add("TensorFlow.jl")`
This will download and build the package.
Including running `deps/build.jl`

You can then tests it, either by running on the REPL: `Pkg.test("TensorFlow")`

Or by navigating to `~/.julia/v0.6/TensorFlow/test`
and running the `runtests.jl` directly.

If one wants to modify the package,
the normal thing to do is to navigate to `~/.julia/v0.6/TensorFlow/` then do a `git checkout` etc from there, and add your fork as an  extra remote if you want to make a PR.


I do not think it is a worth clarifying that you need to run `deps/build.jl`  before running `test/runtests.jl`,
because anyone who does not have `deps/build.jl` run automatically, is probably attempting to get the package in a way that will lead them into far more trouble down the line.

**Comment by RatanRSur** [comment]
Ahh, I did not know that about the intended workflow, thanks for teaching me!
