### ISSUE TITLE
tf.reset_default_graph()  in Julia ?

### ISSUE THREAD

**Issue by Julien281** [malmaud/TensorFlow.jl#374]
Hello

I'm using TensorFlow with Julia and I would like to reduce an expression with the following:

```
cross_entropy = nn.sparse_softmax_cross_entropy_with_logits( logits, labels) 

optimizer = train.GradientDescentOptimizer(learning_rate)

train_op = train.minimize(optimizer,reduce_mean(cross_entropy))
```

I have the following error:

`ERROR: LoadError: Tensorflow error: Status: Node name 'gradients/reduce_19_grad/Reshape' already exists in the Graph`

In python, there is this instruction to avoid the error: `tf.reset_default_graph() `

I don't find the similar command in Julia... Do you know it ?

Thank you

**Comment by oxinabox** [comment]
Replacing your session with a new session witha new graph will do it 
`sess = Session(Graph())`
Or just replacing your graph using `set_default_graph(Graph())`
(but what is the point in a Graph without a session attached?)

We could probably trivially implement `tf.reset_default_graph()`, I'ld need to look at the docs for its exact behavour

**Comment by Julien281** [comment]
There is the same error with the `Session(Graph())` but `set_default_graph()` is not defined... How defines it ?

```
ERROR: LoadError: Tensorflow error: Status: Node name 'gradients/reduce_7_grad/Reshape' already exists in the Graph

ERROR: LoadError: UndefVarError: set_default_graph not defined
```

**Comment by oxinabox** [comment]
`sess = Session(Graph())`  should be called before declaring the compoents of the new graph.
Including before the placeholders

**Comment by Julien281** [comment]
Thank you, the placeholders are fed correctly, but I have still my first error:

`ERROR: LoadError: Tensorflow error: Status: Node name 'gradients/reduce_grad/Reshape' already exists in the Graph`

If I add `set_default_graph(Graph())`, it is not defined:

`ERROR: LoadError: UndefVarError: set_default_graph not defined`

Maybe, there is a library to import ? Or something else ?

**Comment by oxinabox** [comment]
yes there is a library to import, but it doesn't matter because that won't fix your problem, there is something else going on.
In anycase fixing your problem is not in scope for these issues.
I suggest taking your question to stackoverflow, and posting a full MWE. (Feel free to link it here, and I'll maybe take a look.)

We can leave this issue open until we decide if we want to make `tf.reset_default_graph()` in TensorFlow.jl
On the one hand python has it. On the other hand, I am dubious if it is actually useful for anything -- that isn't better severed by `Sesssion(Graph())`, or is so low level that one might as well just use `TensorFlow.set_default_graph(Graph()))`

**Comment by Julien281** [comment]
I posted a similar post to StackOverFlow: https://stackoverflow.com/questions/49411168/tensorflow-julia-node-name-already-exists-in-the-graph

**Comment by oxinabox** [comment]
So this error is what happens if you are using TensorFlow version > 1.4.0
(and as we kinda worked out not directly related to resetting the graph or not)
I am working on getting 1.7.0 working with TensorFlow.jl

**Comment by oxinabox** [comment]
Resolved AFAIK, if issue reoccurs please do file a new issue.
