### ISSUE TITLE
TF_OperationGetAttrTensor

### ISSUE THREAD

**Issue by MikeInnes** [malmaud/TensorFlow.jl#45]
When shape inference runs on tensors I frequently get:
```
ccall: could not find function TF_OperationGetAttrTensor in library
```

For a reproduction you can simply call get_shape on [x here](https://github.com/malmaud/TensorFlow.jl/blob/f2f45d9dd3ec5b242ca0f52a79092b339ada3115/examples/mnist_full.jl#L33), or step through the file line by line in Juno.

Edit: In fact, just running that file seems to cause the error. Do I need to try and get tensorflow master?

I'm also seeing some errors coming from the python process (but the error object is something like `PyCall (None)`) – any ideas why this might be? Could it be caused by a shape mismatch? Let me know how I can help debug.

**Comment by malmaud** [comment]
Two different issues:
* for the `ccall` issue, try rebuilding TensorFlow.jl That function was introduced in a recent version of the tensorflow C library.
* For the python process error, that's probably because the version of TensorFlow installed on the Python side is older than the C library version.

**Comment by MikeInnes** [comment]
Great, thanks, these are good tips. The ccall error is fixed at least now.

This package is shaping up really nicely, by the way – really great work!
